server:
  port: 1234

spring:
  application:
    name: neteam-member
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/users?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Bzy87263416

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.irvine.neteam.common.utils.ResultType